use_frameworks!

target 'JDeepLink_Example' do
    pod 'JDeepLink', :path => '../'

  target 'JDeepLink_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end

pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
    if s.name == 'JDeepLink'
      s.swift_version = '5.0'
    end
  end
end
