use_frameworks!

target 'JDeepLink_Example' do
    pod 'JDeepLink', :path => '../'

  target 'JDeepLink_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end

post_install do |installer|
        installer.pods_project.targets.each do |target|
            if ['Quick', 'Nimble-Snapshots', 'Nimble'].include? target.name
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4'
                end
            end
        end
end
