# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage
# * https://docs.travis-ci.com/user/reference/osx/

osx_image: xcode12.5
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

jobs:
    include:
       - stage: Build And Unit Test
         script:
            - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/JDeepLink.xcworkspace -scheme JDeepLink-Example -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.5' ONLY_ACTIVE_ARCH=NO | xcpretty
       - stage: pod lib lint
         script:
            - pod lib lint
